<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Maren.Application\Maren.Application.csproj" />
    <ProjectReference Include="..\Maren.Shared\Maren.Shared.csproj" />
    <ProjectReference Include="..\Maren.Contracts\Maren.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
