using System.Buffers.Binary;
using System.Security.Cryptography;
using System.Text;
using Org.BouncyCastle.Crypto.Parameters;
using Org.BouncyCastle.Crypto.Signers;

namespace Maren.Infrastructure;

/// <summary>
/// Canonical byte encoding for everything the platform signs, verifies or
/// authenticates. The mirror of <c>CanonicalBytes</c> in the Flutter client.
/// </summary>
/// <remarks>
/// <para>
/// Both sides build the same byte strings independently, so the two encoders
/// have to agree exactly. <c>tests/Maren.Tests/wlos_crypto_vectors.json</c> is
/// generated by the client and verified here; it is the only thing that can
/// prove they do.
/// </para>
/// <para>
/// The traps this exists to avoid are boring and expensive: native integer
/// width, platform endianness, JSON key ordering, and above all GUID byte
/// order. A mismatch in any of them produces signatures that verify on the
/// machine that made them and nowhere else — and the symptom appears at
/// account recovery, which is the worst moment to discover an encoding bug.
/// </para>
/// </remarks>
public static class WlosCanonicalBytes
{
    /// <summary>
    /// A GUID as the sixteen bytes of RFC 4122, big-endian throughout.
    /// </summary>
    /// <remarks>
    /// <b>Never use <c>Guid.ToByteArray()</c> here.</b> The no-argument
    /// overload is mixed-endian: it writes the first three fields
    /// little-endian for compatibility with a Windows struct layout, so it
    /// disagrees with the client on the first four bytes of every identifier.
    /// SQL Server's <c>uniqueidentifier</c> orders its bytes differently
    /// again. This is the single most likely cross-language mismatch in WLOS
    /// and a vector pins it.
    /// </remarks>
    public static byte[] Uuid(Guid value) => value.ToByteArray(bigEndian: true);

    public static byte[] UInt16BigEndian(int value)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(value);
        ArgumentOutOfRangeException.ThrowIfGreaterThan(value, ushort.MaxValue);
        var buffer = new byte[2];
        BinaryPrimitives.WriteUInt16BigEndian(buffer, (ushort)value);
        return buffer;
    }

    public static byte[] UInt32BigEndian(long value)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(value);
        ArgumentOutOfRangeException.ThrowIfGreaterThan(value, uint.MaxValue);
        var buffer = new byte[4];
        BinaryPrimitives.WriteUInt32BigEndian(buffer, (uint)value);
        return buffer;
    }

    /// <summary>
    /// A protocol label, UTF-8 encoded. Labels are compile-time ASCII
    /// constants, never user input, so there is no normalisation question.
    /// </summary>
    public static byte[] Label(string ascii)
    {
        foreach (var c in ascii)
        {
            if (c > 0x7F)
                throw new ArgumentException("label must be ASCII", nameof(ascii));
        }

        return Encoding.UTF8.GetBytes(ascii);
    }

    public static byte[] Concat(params byte[][] parts)
    {
        var total = 0;
        foreach (var p in parts) total += p.Length;

        var output = new byte[total];
        var offset = 0;
        foreach (var p in parts)
        {
            p.CopyTo(output, offset);
            offset += p.Length;
        }

        return output;
    }
}

/// <summary>
/// The HKDF labels that separate one derived key from another.
/// </summary>
/// <remarks>
/// <b>These are the protocol.</b> <c>Auth</c> is what reaches this server;
/// <c>KekPassword</c> is what opens her journal and never leaves her device.
/// They are different outputs of the same master under different info strings,
/// and that difference is the entire reason the server cannot read anything it
/// stores. They are listed here so the server can verify the client's
/// derivation against a vector, and for no other purpose — nothing on this
/// side ever derives <c>KekPassword</c>, because nothing on this side ever
/// holds a master secret.
/// </remarks>
public static class WlosKdfLabels
{
    public const string Auth = "WLOS/v1/auth";
    public const string KekPassword = "WLOS/v1/kek/pw";
    public const string KekRecovery = "WLOS/v1/kek/recovery";
    public const string RecoverySign = "WLOS/v1/recovery/sign";
}

/// <summary>
/// How the server stores what the client sends as an authentication secret.
/// </summary>
/// <remarks>
/// <para>
/// <b>S2, locked at the crypto checkpoint: salted HMAC-SHA256, and no further
/// stretching.</b> The input is already a 32-byte Argon2id output derived on
/// her device, so it is high-entropy by construction. An attacker holding this
/// table still has to run Argon2id once per password guess, and that cost
/// dominates a hash here by orders of magnitude.
/// </para>
/// <para>
/// Adding PBKDF2 on top would look like defence in depth and would mostly be
/// decoration — it protects against nothing the Argon2id stage has not already
/// made expensive, and it invites the belief that the server is doing
/// password hashing. It is not. <b>The server never receives a password.</b>
/// </para>
/// </remarks>
public static class AuthSecretVerifier
{
    /// <summary>HMAC-SHA256 keyed by the per-row salt, over the auth secret.</summary>
    public static byte[] Compute(ReadOnlySpan<byte> authSecret, ReadOnlySpan<byte> salt)
    {
        Span<byte> destination = stackalloc byte[32];
        HMACSHA256.HashData(salt, authSecret, destination);
        return destination.ToArray();
    }

    /// <summary>
    /// Constant-time comparison. A short-circuiting compare on a credential
    /// verifier leaks how much of it matched.
    /// </summary>
    public static bool Verify(
        ReadOnlySpan<byte> authSecret, ReadOnlySpan<byte> salt, ReadOnlySpan<byte> expected)
        => CryptographicOperations.FixedTimeEquals(Compute(authSecret, salt), expected);
}

/// <summary>
/// Ed25519 signature verification, for the recovery proof of possession.
/// </summary>
/// <remarks>
/// <para>
/// <b>Verification only.</b> This server holds the public half of a key
/// derived from her recovery entropy, and nothing else. It cannot sign, cannot
/// derive the private key, and cannot open anything the matching wrapping key
/// opens — that key comes from the same entropy under a different HKDF label
/// and never leaves her device.
/// </para>
/// <para>
/// <b>Why BouncyCastle (S1).</b> .NET 10 has no standalone Ed25519: the only
/// references to it in the framework are composite post-quantum algorithm
/// identifiers (<c>MLDsa44WithEd25519</c>), which are a different construction
/// and not a plain verifier. Both BouncyCastle and NSec were spiked against
/// RFC 8032 test vector 1 and both passed. NSec is smaller and faster
/// (0.14 ms versus 0.26 ms per verification) but binds a native libsodium
/// binary per runtime identifier. This is a rarely-used path that has to work
/// when a woman is locked out of her account, and a missing or mismatched
/// native binary fails exactly there. A managed dependency with no native
/// assets is worth 5 MB and a tenth of a millisecond.
/// </para>
/// </remarks>
public static class RecoverySignatureVerifier
{
    public const int PublicKeyLength = 32;
    public const int SignatureLength = 64;

    /// <summary>
    /// True when <paramref name="signature"/> is a valid Ed25519 signature
    /// over <paramref name="message"/> under <paramref name="publicKey"/>.
    /// </summary>
    /// <remarks>
    /// Returns false for every failure, including a malformed key or
    /// signature. A caller must not be able to distinguish "wrong signature"
    /// from "wrong length" from "unknown account" — the reset path returns one
    /// generic failure for all of them, and that starts here.
    /// </remarks>
    public static bool Verify(
        ReadOnlySpan<byte> publicKey, ReadOnlySpan<byte> message, ReadOnlySpan<byte> signature)
    {
        if (publicKey.Length != PublicKeyLength || signature.Length != SignatureLength)
            return false;

        try
        {
            var verifier = new Ed25519Signer();
            verifier.Init(false, new Ed25519PublicKeyParameters(publicKey.ToArray(), 0));
            verifier.BlockUpdate(message.ToArray(), 0, message.Length);
            return verifier.VerifySignature(signature.ToArray());
        }
        catch (Exception)
        {
            // A malformed point, a bad encoding — all of it is "no".
            return false;
        }
    }
}

/// <summary>
/// The bytes a device signs to prove it holds the recovery phrase.
/// </summary>
/// <remarks>
/// <para>
/// <c>"WLOS/v1/recovery-reset" ‖ challengeId(16) ‖ nonce(32)</c> — seventy
/// bytes, fixed width. The mirror of <c>RecoveryContext</c> in the client, and
/// a vector pins the two together.
/// </para>
/// <para>
/// <b>No account reference</b>, which differs from the specification text.
/// That text assumed a context carrying <c>accountRef</c> and a hash of the
/// new credential material, and on this path the signer knows neither: she is
/// not signed in, and she cannot choose a new password until the wrapper has
/// opened, which happens after this signature. Binding something the signer
/// cannot know is not a stronger binding — it is one nobody can produce. The
/// challenge id names the account on this side, where the lookup happens, and
/// it is single-use.
/// </para>
/// </remarks>
public static class WlosRecoveryContext
{
    public const string Label = "WLOS/v1/recovery-reset";

    public static byte[] Build(Guid challengeId, ReadOnlySpan<byte> nonce)
    {
        if (nonce.Length != 32)
            throw new ArgumentException("nonce must be 32 bytes", nameof(nonce));

        return WlosCanonicalBytes.Concat(
            WlosCanonicalBytes.Label(Label),
            WlosCanonicalBytes.Uuid(challengeId),
            nonce.ToArray());
    }
}
