<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Maren.Application\Maren.Application.csproj" />
    <ProjectReference Include="..\Maren.Persistence\Maren.Persistence.csproj" />
    <ProjectReference Include="..\Maren.Infrastructure\Maren.Infrastructure.csproj" />
    <ProjectReference Include="..\Maren.Contracts\Maren.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
